name: Deploy Multi-Environment

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.repository }}-deploy-dev
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.VPS_IP }}:5000/router-api-dev:latest .

      - name: Push image to private registry
        run: |
          docker push ${{ secrets.VPS_IP }}:5000/router-api-dev:latest

      - name: SSH Deploy DEV
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_DEV_HOST }}
          username: ${{ secrets.VPS_DEV_USER }}
          key: ${{ secrets.VPS_DEV_SSH_KEY }}
          script: |
            set -e
            cd deploy/dev/

            cd ../infra
            git fetch origin && git checkout develop && git pull

            cd ./APIs
            docker compose pull router-api-dev
            docker compose up -d router-api-dev

          debug: true
